"""empty message

Revision ID: 16d4472f7b65
Revises: 1018d82115b4
Create Date: 2023-11-05 19:03:38.369900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16d4472f7b65'
down_revision: Union[str, None] = '1018d82115b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_records_email', table_name='records')
    op.create_index(op.f('ix_records_email'), 'records', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_records_email'), table_name='records')
    op.create_index('ix_records_email', 'records', ['email'], unique=False)
    # ### end Alembic commands ###
