"""empty message

Revision ID: d513f4e6342b
Revises: 1d841888e18e
Create Date: 2023-12-06 21:30:43.261320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd513f4e6342b'
down_revision: Union[str, None] = '1d841888e18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('emails_from_description', sa.String(), nullable=True))
    op.create_index(op.f('ix_records_emails_from_description'), 'records', ['emails_from_description'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_records_emails_from_description'), table_name='records')
    op.drop_column('records', 'emails_from_description')
    # ### end Alembic commands ###
